version: 2.1

jobs:      
  build-image-no-cache:
    machine: true
    steps:
      - checkout
      - run: docker build . -t $CIRCLE_WORKFLOW_ID
      
  build-no-cache-buildkit:
    machine: true
    environment:
      DOCKER_BUILDKIT: '1'
    steps:
      - checkout
      - run: docker build . -t $CIRCLE_WORKFLOW_ID
  
  dlc-test:
    machine:
      image: << parameters.image-version >>
      docker_layer_caching: true
    parameters:
      image-version: 
        type: string
    environment: 
      DOCKER_BULDKIT: '1'
    steps:
      - checkout
      - run: df -h
      - run:
          name: display contents of docker daemon
          command: |
              [ -f /etc/docker/daemon.json ] && cat /etc/docker/daemon.json || echo "File /etc/docker/daemon.json does not exist"
      - run: docker version
      - run: systemctl status docker
      - run: 
          name: Fetch AMI ID from Instance Metadata for reference
          command: |
             TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
             && curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/ami-id
      - run: docker build . -t node-image --cache-from=node-image --build-arg BUILDKIT_INLINE_CACHE=1
      
workflows:
  ubuntu-2004:
    jobs:
      - dlc-test:           
             matrix:
               parameters:
                  image-version: ["ubuntu-2004:2024.05.1", "ubuntu-2004:2023.10.1", "ubuntu-2004:2024.04.4"]
  ubuntu-2404:
    jobs:
      - dlc-test:           
             matrix:
               parameters:
                  image-version: ["ubuntu-2404:2024.05.1"]
  ubuntu-2204:
      jobs:
        - dlc-test:
            matrix:
              parameters:
                image-version: ["ubuntu-2204:2024.05.1", "ubuntu-2204:2024.01.1", "ubuntu-2204:2023.10.1"] 
